### ISSUE TITLE
Consider URLSearchParams

### ISSUE THREAD

**Issue by Maximilian5189** [roonie007/axiod#12]
Hi,

at the moment FormData is supported as body, and is handed to fetch without modification (mod.ts:78).

How about doing the same for URLSearchParams? In fetch both types are treated differently, e.g. for URLSearchParams the content-type header is set to application/x-www-form-urlencoded;charset=UTF-8, whereas FormData is treated as multipart/form-data. So in my opinion it would make sense to consider these scenarios in axiod as well. What do you think?

**Comment by roonie007** [comment]
Hey @Maximilian5189 

Can you create PR for this ?

**Comment by Maximilian5189** [comment]
Yes, just created the PR.

**Comment by roonie007** [comment]
Thanks, it's merged and available in [0.23](https://github.com/roonie007/axiod/releases/tag/0.23)
