### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by maxime-gautre** [roonie007/axiod#13]
Hello, I think that the latest versions are not published on the deno land registry.

For example, here is an example of code where the queryParams are passed via the params parameter:

```typescript
async function fetchArtworks() {
  const params = {
    fields: 'id,title',
    page: 10
  }
  const config = {
    url: `https://api.artic.edu/api/v1/artworks`,
    method: "get" as const,
    params,
  };

  const res = await axiod.request(config);
  console.log('res', res)
  return res.data;
}

void fetchArtworks()
```

When I run it with the import: 

```typescript 
import axiod from "https://deno.land/x/axiod/mod.ts";
```
all fields are returned and the page is not the right one.

However, when I use the import:
```typescript 
import axiod from "https://raw.githubusercontent.com/roonie007/axiod/master/mod.ts";
```
it works correctly. 

The last release is from August 2020 and [the commit](https://github.com/roonie007/axiod/commit/7a484af0acef539a5b4023a7ca50f05cb01ff02f) that fixes the problem is from November 2020. Is there any plan to publish the latest versions on the deno land registry ?

**Comment by roonie007** [comment]
@maxime-gautre it's done https://deno.land/x/axiod@0.21, feel free to close the issue after you test it directly from deno.land

**Comment by maxime-gautre** [comment]
@roonie007 Thank you, it works like a charm.
