### ISSUE TITLE
Type Generics

### ISSUE THREAD

**Issue by kaaax0815** [roonie007/axiod#16]
Axios supports Type Generics
https://github.com/axios/axios/blob/82c94555917834770bd1389fc0b4cd9ba35ec3fe/index.d.ts#L151
and
https://github.com/axios/axios/blob/82c94555917834770bd1389fc0b4cd9ba35ec3fe/index.d.ts#L83
so if you now the response type you can easily create a interface pass it to the post request like
```ts
const data = await axios.post<Result>();

data.data // Autocomplete because `data.data` is `typeof Result`

interface Result {
nice: string;
data: string;
}
```

**Comment by roonie007** [comment]
I will try to add this as soon as possible
