### ISSUE TITLE
[Feature request] Interceptors

### ISSUE THREAD

**Issue by tianalemesle** [roonie007/axiod#22]
Cf. [Interceptors | Axios Docs](https://axios-http.com/docs/interceptors)

Thanks

**Comment by roonie007** [comment]
@tianalemesle , can you open a PR ?

**Comment by tianalemesle** [comment]
I am requesting this feature but am not qualified to re-implement it myself, sorry

**Comment by roonie007** [comment]
@tianalemesle np, I will try to implement it as soon I have some freetime

**Comment by roonie007** [comment]
@tianalemesle added in [0.25.0](https://github.com/roonie007/axiod/releases/tag/0.25.0)
