### ISSUE TITLE
[Feature Request] Add More Parse Type

### ISSUE THREAD

**Issue by Kayxue** [roonie007/axiod#23]
Can you add more type to auto parse (e.g. ArrayBuffer) please?
And also add responseType to request Options

**Comment by roonie007** [comment]
@Kayxue can you open a PR ?

**Comment by Kayxue** [comment]
I don’t know.
Maybe I can try my best to find out how to modify? 🤔🤔🤔

**Comment by roonie007** [comment]
@Kayxue published under [0.26.0](https://github.com/roonie007/axiod/releases/tag/0.26.0)
