### ISSUE TITLE
responseType

### ISSUE THREAD

**Issue by dvadvaa** [roonie007/axiod#3]
Hello. The example from the readme returns an error. Problem with **responseType**.

Example code:

`axiod({
        method: "get",
        url: "http://bit.ly/2mTM3nY",
        responseType: "stream",
    }).then((response) => {
        response.data.pipe(fs.createWriteStream("ada_lovelace.jpg"));
    });
`

Error: 

`[ERROR]: Argument of type '{ method: string; url: string; responseType: string; }' is not assignable to parameter of type 'string | IRequest'.
  Object literal may only specify known properties, and 'responseType' does not exist in type 'IRequest'.
`

**Comment by roonie007** [comment]
@dvadvaa I will check it this weekend

**Comment by dvadvaa** [comment]
Good!

**Comment by roonie007** [comment]
Resolved in this PR #18

**Comment by TheJizel** [comment]
FYI - this is still an issue

**Comment by roonie007** [comment]
@TheJizel can you give an example ?
